# chunk5_excel_report.py
import os
import json
from dotenv import load_dotenv
from openpyxl import Workbook
from openpyxl.styles import (Font, PatternFill, Alignment,
                              Border, Side, GradientFill)
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule, DataBarRule
from openpyxl.chart import BarChart, Reference
from openpyxl.chart.series import SeriesLabel

load_dotenv()

# ── colours ───────────────────────────────────────────────────────────────────
NAVY        = "1E3A5F"
BLUE2       = "2E6DA4"
TEAL        = "0F6E56"
RED_DK      = "8B1A1A"
RED_LT      = "FCEBEB"
AMBER_DK    = "7B5000"
AMBER_LT    = "FFF3CD"
GREEN_DK    = "1A5C38"
GREEN_LT    = "D6F0E4"
GRAY_LT     = "F5F5F5"
GRAY_MD     = "D8DCE3"
WHITE       = "FFFFFF"
GOLD        = "C8973A"
PURPLE      = "3C3489"
PURPLE_LT   = "EEEDFE"

def fill(hex_c):
    return PatternFill("solid",
                       start_color=hex_c,
                       end_color=hex_c)

def font(bold=False, color="000000",
         size=10, italic=False, name="Calibri"):
    return Font(bold=bold, color=color,
                size=size, italic=italic, name=name)

def border(style="thin", color="D0D0D0"):
    s = Side(style=style, color=color)
    return Border(left=s, right=s, top=s, bottom=s)

def align(h="left", v="center", wrap=False):
    return Alignment(horizontal=h,
                     vertical=v,
                     wrap_text=wrap)

def write(ws, row, col, value,
          bold=False, fnt_color="000000",
          fnt_size=10, bg=None,
          h_align="left", wrap=False,
          italic=False, bdr=True):
    cell            = ws.cell(row=row, column=col, value=value)
    cell.font       = font(bold=bold, color=fnt_color,
                           size=fnt_size, italic=italic)
    cell.alignment  = align(h_align, wrap=wrap)
    if bg:
        cell.fill   = fill(bg)
    if bdr:
        cell.border = border()
    return cell


# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — VENDOR COMPARISON
# ══════════════════════════════════════════════════════════════════════════════
def build_comparison_tab(ws, extracted: dict,
                         scores: dict, risks: dict):
    ws.title       = "📊 Vendor Comparison"
    ws.sheet_view.showGridLines = False

    # ── title row ─────────────────────────────────────────────────────────────
    ws.row_dimensions[1].height = 34
    ws.merge_cells("A1:P1")
    c = ws["A1"]
    c.value     = "RFQ VENDOR COMPARISON — HR Steel Sheets 3mm | Qty: 10,000 Kg"
    c.font      = font(bold=True, color=WHITE, size=13)
    c.fill      = fill(NAVY)
    c.alignment = align("center")

    # ── sub-header ────────────────────────────────────────────────────────────
    ws.row_dimensions[2].height = 18
    ws.merge_cells("A2:P2")
    c = ws["A2"]
    c.value     = (f"Generated by RFQ Intelligence Agent  |  "
                   f"Procurement Policy Rev 4.1 Applied  |  "
                   f"All prices in INR")
    c.font      = font(italic=True, color=WHITE, size=8)
    c.fill      = fill(BLUE2)
    c.alignment = align("center")

    # ── column headers ────────────────────────────────────────────────────────
    headers = [
        ("Rank",            8),  ("Vendor Name",      28),
        ("Unit Price\n(INR/Kg)", 14), ("Freight\n(INR/Kg)", 12),
        ("Incoterm",        13), ("GST %",             8),
        ("Landed Cost\n(INR/Kg)", 14), ("Delivery\n(Days)",  12),
        ("Payment\nTerms",  18), ("Advance\n%",         9),
        ("Validity\n(Days)", 11), ("Certifications",   20),
        ("Warranty\n(Mo)",   10), ("Penalty\nClause",  20),
        ("Price\nFirm",      9), ("Risk\nLevel",       11),
    ]

    ws.row_dimensions[3].height = 36
    for col_idx, (h, w) in enumerate(headers, 1):
        ws.column_dimensions[get_column_letter(col_idx)].width = w
        c = ws.cell(row=3, column=col_idx, value=h)
        c.font       = font(bold=True, color=WHITE, size=9)
        c.fill       = fill(NAVY)
        c.alignment  = align("center", wrap=True)
        c.border     = border("thin", "FFFFFF")

    # ── rank vendors by score ─────────────────────────────────────────────────
    vendor_list = []
    for vname, fields in extracted.items():
        score_data = scores.get(vname, {})
        risk_data  = risks.get(vname,  {})
        vendor_list.append({
            "name":    vname,
            "fields":  fields,
            "score":   score_data.get("total_score", 0),
            "risk":    risk_data
        })
    vendor_list.sort(key=lambda x: x["score"], reverse=True)

    # ── data rows ─────────────────────────────────────────────────────────────
    for row_offset, v in enumerate(vendor_list):
        row        = 4 + row_offset
        ws.row_dimensions[row].height = 30
        f          = v["fields"]
        risk       = v["risk"]
        score      = v["score"]
        rank       = row_offset + 1
        disq       = risk.get("disqualify_recommended", False)
        risk_level = risk.get("overall_risk_level", "MEDIUM")
        red_count  = risk.get("red_count", 0)
        amb_count  = risk.get("amber_count", 0)

        # row background
        if disq:
            row_bg = RED_LT
        elif rank == 1:
            row_bg = GREEN_LT
        elif rank == 2:
            row_bg = "EAF6FF"
        elif rank == 3:
            row_bg = PURPLE_LT
        elif amb_count > 0:
            row_bg = AMBER_LT
        else:
            row_bg = GRAY_LT if row_offset % 2 == 0 else WHITE

        # rank cell
        rank_label = {1:"🥇 1st", 2:"🥈 2nd",
                      3:"🥉 3rd"}.get(rank, f"  #{rank}")
        if disq:
            rank_label = "⛔ DISQ"
        write(ws, row, 1, rank_label,
              bold=True, fnt_color=NAVY if not disq else RED_DK,
              bg=row_bg, h_align="center", fnt_size=9)

        # vendor name
        write(ws, row, 2, v["name"],
              bold=(rank <= 3), fnt_size=9,
              fnt_color=GREEN_DK if rank==1 else
                        RED_DK if disq else "000000",
              bg=row_bg)

        # unit price
        up = f.get("unit_price")
        write(ws, row, 3, f"₹{up:.2f}" if up else "N/A",
              h_align="right", bg=row_bg, fnt_size=9)

        # freight
        fr = f.get("freight_per_unit", 0) or 0
        write(ws, row, 4,
              f"₹{fr:.2f}" if fr > 0 else "Included",
              h_align="right", bg=row_bg, fnt_size=9,
              italic=(fr == 0))

        # incoterm
        write(ws, row, 5, f.get("incoterm", "N/A"),
              h_align="center", bg=row_bg, fnt_size=9)

        # gst
        gst = f.get("gst_rate", 18)
        write(ws, row, 6, f"{gst}%",
              h_align="center", bg=row_bg, fnt_size=9)

        # landed cost — highlight lowest
        lc = f.get("landed_cost", 0) or 0
        all_lc = [vv["fields"].get("landed_cost", 0) or 0
                  for vv in vendor_list]
        is_lowest = lc > 0 and lc == min(c for c in all_lc if c > 0)
        lc_cell = write(ws, row, 7, f"₹{lc:.2f}" if lc else "N/A",
                        bold=is_lowest,
                        fnt_color=GREEN_DK if is_lowest else "000000",
                        bg=GREEN_LT if is_lowest else row_bg,
                        h_align="right", fnt_size=9)

        # delivery days
        dd = f.get("delivery_days")
        dd_bg = (GREEN_LT if dd and dd <= 10 else
                 AMBER_LT if dd and dd <= 21 else
                 RED_LT   if dd and dd > 21 else row_bg)
        write(ws, row, 8, dd if dd else "N/A",
              h_align="center", bg=dd_bg, fnt_size=9)

        # payment terms
        write(ws, row, 9,
              str(f.get("payment_terms", "N/A"))[:30],
              bg=row_bg, fnt_size=9)

        # advance %
        adv    = f.get("advance_percentage", 0) or 0
        adv_bg = (RED_LT   if adv >= 100 else
                  AMBER_LT if adv >= 25  else
                  GREEN_LT if adv == 0   else row_bg)
        write(ws, row, 10,
              f"{adv}%" if adv > 0 else "None",
              h_align="center",
              fnt_color=RED_DK if adv >= 50 else "000000",
              bold=(adv >= 50),
              bg=adv_bg, fnt_size=9)

        # validity
        val    = f.get("quote_validity_days", 30) or 30
        val_bg = (RED_LT   if val <= 5  else
                  AMBER_LT if val <= 15 else row_bg)
        write(ws, row, 11, f"{val} days",
              h_align="center", bg=val_bg, fnt_size=9)

        # certifications
        certs = f.get("certifications", []) or []
        cert_str = ", ".join(certs) if certs else "❌ NONE"
        cert_bg  = (RED_LT   if not certs else
                    AMBER_LT if len(certs) == 1 else row_bg)
        write(ws, row, 12, cert_str,
              fnt_color=RED_DK if not certs else "000000",
              bg=cert_bg, fnt_size=9, wrap=True)

        # warranty
        war    = f.get("warranty_months", 0) or 0
        war_bg = (RED_LT   if war == 0   else
                  AMBER_LT if war < 12   else row_bg)
        write(ws, row, 13,
              f"{war} mo" if war > 0 else "None",
              h_align="center", bg=war_bg, fnt_size=9)

        # penalty clause
        pen = f.get("penalty_clause")
        write(ws, row, 14,
              pen if pen else "⚠ Not offered",
              fnt_color=RED_DK if not pen else "000000",
              italic=not bool(pen),
              bg=AMBER_LT if not pen else row_bg,
              fnt_size=8, wrap=True)

        # price firm
        pf    = f.get("price_firm")
        pf_bg = GREEN_LT if pf else RED_LT
        write(ws, row, 15,
              "✅ Firm" if pf else "⚠ Variable",
              h_align="center",
              fnt_color=GREEN_DK if pf else RED_DK,
              bold=True, bg=pf_bg, fnt_size=9)

        # risk level
        risk_colors = {
            "LOW":      (GREEN_DK, GREEN_LT),
            "MEDIUM":   (AMBER_DK, AMBER_LT),
            "HIGH":     (RED_DK,   RED_LT),
            "CRITICAL": (RED_DK,   RED_LT),
        }
        rc, rb = risk_colors.get(risk_level, ("000000", row_bg))
        rl_icon = {"LOW":"🟢","MEDIUM":"🟡",
                   "HIGH":"🔴","CRITICAL":"🔴"}.get(risk_level,"")
        write(ws, row, 16,
              f"{rl_icon} {risk_level}",
              h_align="center",
              fnt_color=rc, bold=(risk_level in ["HIGH","CRITICAL"]),
              bg=rb, fnt_size=9)

    # ── legend ────────────────────────────────────────────────────────────────
    leg_row = 4 + len(vendor_list) + 1
    ws.merge_cells(
        f"A{leg_row}:{get_column_letter(16)}{leg_row}")
    c = ws.cell(row=leg_row, column=1,
                value=("🥇 Recommended   🔵 Consider   "
                       "🟡 Caution — amber flags present   "
                       "⛔ DISQUALIFIED — red flags present   "
                       "🟩 Lowest landed cost"))
    c.font      = font(italic=True, color="5A5F6B", size=8)
    c.fill      = fill(GRAY_LT)
    c.alignment = align("center")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — SCORECARD
# ══════════════════════════════════════════════════════════════════════════════
def build_scorecard_tab(ws, scores: dict, risks: dict):
    ws.title = "🏆 Scorecard"
    ws.sheet_view.showGridLines = False

    # title
    ws.row_dimensions[1].height = 30
    ws.merge_cells("A1:I1")
    c = ws["A1"]
    c.value     = "VENDOR SCORECARD — WEIGHTED EVALUATION RESULTS"
    c.font      = font(bold=True, color=WHITE, size=12)
    c.fill      = fill(NAVY)
    c.alignment = align("center")

    # weights sub-header
    ws.row_dimensions[2].height = 18
    ws.merge_cells("A2:I2")
    c = ws["A2"]
    c.value = ("Price 40%  |  Delivery 25%  |  "
               "Payment 20%  |  Quality 10%  |  Penalty 5%")
    c.font      = font(italic=True, color=WHITE, size=9)
    c.fill      = fill(BLUE2)
    c.alignment = align("center")

    # column headers
    sc_headers = [
        ("Rank",       8), ("Vendor",     28),
        ("Price\n/40", 12), ("Delivery\n/25", 12),
        ("Payment\n/20", 12), ("Quality\n/10", 12),
        ("Penalty\n/5", 10), ("TOTAL\n/100", 12),
        ("Category",   16),
    ]
    ws.row_dimensions[3].height = 32
    for ci, (h, w) in enumerate(sc_headers, 1):
        ws.column_dimensions[get_column_letter(ci)].width = w
        c = ws.cell(row=3, column=ci, value=h)
        c.font      = font(bold=True, color=WHITE, size=9)
        c.fill      = fill(TEAL)
        c.alignment = align("center", wrap=True)
        c.border    = border()

    # sort vendors by score
    sorted_vendors = sorted(
        scores.items(),
        key=lambda x: x[1].get("total_score", 0),
        reverse=True
    )

    for ri, (vname, sdata) in enumerate(sorted_vendors):
        row  = 4 + ri
        rank = ri + 1
        ws.row_dimensions[row].height = 26
        cs   = sdata.get("criteria_scores", {})
        tot  = sdata.get("total_score", 0)
        cat  = sdata.get("rank_category", "")
        disq = risks.get(vname, {}).get(
            "disqualify_recommended", False)

        # row bg
        row_bg = (RED_LT    if disq      else
                  GREEN_LT  if rank == 1 else
                  "EAF6FF"  if rank == 2 else
                  PURPLE_LT if rank == 3 else
                  GRAY_LT   if ri%2==0   else WHITE)

        # rank
        medal  = {1:"🥇",2:"🥈",3:"🥉"}.get(rank, str(rank))
        write(ws, row, 1, medal,
              h_align="center", bg=row_bg, fnt_size=11,
              bold=(rank<=3))

        # vendor name
        write(ws, row, 2, vname, bold=(rank<=3),
              fnt_color=(RED_DK if disq else
                         GREEN_DK if rank==1 else "000000"),
              bg=row_bg, fnt_size=9)

        # criteria scores
        criteria_order = [
            "price","delivery","payment","quality","penalty"]
        for ci, crit in enumerate(criteria_order):
            crit_score = cs.get(crit, {})
            ws_score   = crit_score.get("weighted_score", 0)
            raw        = crit_score.get("raw_score", 0)
            reasoning  = crit_score.get("reasoning", "")
            col        = 3 + ci

            # colour based on raw score
            s_bg = (GREEN_LT if raw >= 80 else
                    AMBER_LT if raw >= 50 else
                    RED_LT   if raw < 50  else row_bg)
            if disq:
                s_bg = RED_LT

            c = ws.cell(row=row, column=col,
                        value=round(ws_score, 1))
            c.font      = font(bold=(raw>=80), size=9,
                               color=(GREEN_DK if raw>=80 else
                                      RED_DK   if raw<50  else
                                      "000000"))
            c.fill      = fill(s_bg)
            c.alignment = align("center")
            c.border    = border()
            c.comment   = None  # could add openpyxl Comment

        # total
        tot_bg = (RED_LT    if tot < 40  else
                  AMBER_LT  if tot < 65  else
                  GREEN_LT  if tot >= 80 else
                  GRAY_LT)
        c = ws.cell(row=row, column=8,
                    value=round(tot, 1))
        c.font      = font(bold=True, size=11,
                           color=(GREEN_DK if tot>=80 else
                                  RED_DK   if tot<50  else
                                  AMBER_DK))
        c.fill      = fill(tot_bg)
        c.alignment = align("center")
        c.border    = border()

        # category
        cat_icons = {
            "Recommended": ("✅ Recommended", GREEN_DK, GREEN_LT),
            "Consider":    ("🔵 Consider",    BLUE2,    "E6F1FB"),
            "Caution":     ("🟡 Caution",     AMBER_DK, AMBER_LT),
            "Avoid":       ("🔴 Avoid",       RED_DK,   RED_LT),
        }
        if disq:
            label, fc, bc = "⛔ DISQUALIFIED", RED_DK, RED_LT
        else:
            label, fc, bc = cat_icons.get(
                cat, (cat, "000000", row_bg))
        write(ws, row, 9, label,
              fnt_color=fc, bold=True,
              bg=bc, h_align="center", fnt_size=9)

    # reasoning section
    reason_row = 4 + len(sorted_vendors) + 2
    ws.row_dimensions[reason_row].height = 20
    ws.merge_cells(
        f"A{reason_row}:I{reason_row}")
    c = ws.cell(row=reason_row, column=1,
                value="SCORING REASONING (from Mistral AI):")
    c.font      = font(bold=True, color=WHITE, size=9)
    c.fill      = fill(TEAL)
    c.alignment = align("left")

    for ri, (vname, sdata) in enumerate(sorted_vendors):
        rr  = reason_row + 1 + ri
        ws.row_dimensions[rr].height = 18
        ws.merge_cells(f"A{rr}:I{rr}")
        rank = ri + 1
        summ = sdata.get("one_line_summary", "")
        c    = ws.cell(row=rr, column=1,
                       value=f"#{rank}  {vname}:  {summ}")
        c.font      = font(size=8, italic=True,
                           color=("5A5F6B"))
        c.fill      = fill(GRAY_LT if ri%2==0 else WHITE)
        c.alignment = align("left")


# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — RISK FLAGS
# ══════════════════════════════════════════════════════════════════════════════
def build_flags_tab(ws, risks: dict):
    ws.title = "🚩 Risk Flags"
    ws.sheet_view.showGridLines = False

    # title
    ws.row_dimensions[1].height = 30
    ws.merge_cells("A1:G1")
    c = ws["A1"]
    c.value     = "RISK FLAGS & COMPLIANCE ALERTS"
    c.font      = font(bold=True, color=WHITE, size=12)
    c.fill      = fill(RED_DK)
    c.alignment = align("center")

    # headers
    flag_hdrs = [
        ("Vendor",     28), ("Flag ID",    9),
        ("Severity",   11), ("Category",  18),
        ("Condition",  35), ("Detail",    52),
        ("Action Required", 38),
    ]
    ws.row_dimensions[2].height = 24
    for ci, (h, w) in enumerate(flag_hdrs, 1):
        ws.column_dimensions[get_column_letter(ci)].width = w
        c = ws.cell(row=2, column=ci, value=h)
        c.font      = font(bold=True, color=WHITE, size=9)
        c.fill      = fill(RED_DK)
        c.alignment = align("center", wrap=True)
        c.border    = border()

    current_row = 3
    for vname, rdata in risks.items():
        flags = rdata.get("all_flags", [])
        if not flags:
            # vendor row with no flags
            ws.row_dimensions[current_row].height = 20
            ws.merge_cells(
                f"A{current_row}:G{current_row}")
            c = ws.cell(row=current_row, column=1,
                        value=f"✅  {vname} — No flags detected")
            c.font      = font(size=9, color=GREEN_DK)
            c.fill      = fill(GREEN_LT)
            c.alignment = align("left")
            c.border    = border()
            current_row += 1
            continue

        for flag in flags:
            ws.row_dimensions[current_row].height = 40
            sev  = flag.get("severity", "AMBER")
            s_fg = (RED_DK   if sev=="RED"  else
                    AMBER_DK if sev=="AMBER" else
                    BLUE2)
            s_bg = (RED_LT   if sev=="RED"  else
                    AMBER_LT if sev=="AMBER" else
                    "E6F1FB")

            write(ws, current_row, 1, vname,
                  bold=True, fnt_size=9,
                  fnt_color=(RED_DK if sev=="RED" else "000000"),
                  bg=s_bg)
            write(ws, current_row, 2,
                  flag.get("flag_id",""),
                  h_align="center", bg=s_bg,
                  fnt_size=9, bold=True)

            # severity pill
            sev_icon = {"RED":"🔴 RED",
                        "AMBER":"🟡 AMBER",
                        "INFO":"ℹ INFO"}.get(sev, sev)
            write(ws, current_row, 3, sev_icon,
                  h_align="center",
                  fnt_color=s_fg, bold=True,
                  bg=s_bg, fnt_size=9)

            write(ws, current_row, 4,
                  flag.get("category",""),
                  bg=s_bg, fnt_size=9)
            write(ws, current_row, 5,
                  flag.get("condition",""),
                  bg=s_bg, fnt_size=9,
                  bold=(sev=="RED"), wrap=True)
            write(ws, current_row, 6,
                  flag.get("detail",""),
                  bg=s_bg, fnt_size=8,
                  italic=True, wrap=True)
            write(ws, current_row, 7,
                  flag.get("action",""),
                  bg=s_bg, fnt_size=8,
                  fnt_color=s_fg, bold=(sev=="RED"),
                  wrap=True)
            current_row += 1

    # summary section
    sum_row = current_row + 1
    ws.merge_cells(
        f"A{sum_row}:G{sum_row}")
    c = ws.cell(row=sum_row, column=1,
                value="DISQUALIFIED VENDORS:")
    c.font = font(bold=True, color=WHITE, size=9)
    c.fill = fill(RED_DK)
    c.alignment = align("left")

    disq_vendors = [
        v for v, r in risks.items()
        if r.get("disqualify_recommended")]
    for i, vname in enumerate(disq_vendors):
        dr = sum_row + 1 + i
        ws.merge_cells(f"A{dr}:G{dr}")
        c  = ws.cell(row=dr, column=1,
                     value=f"⛔  {vname} — "
                           f"DISQUALIFIED. "
                           f"Do not include in PO selection.")
        c.font      = font(bold=True, size=9,
                           color=RED_DK)
        c.fill      = fill(RED_LT)
        c.alignment = align("left")
        c.border    = border()


# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 — RECOMMENDATION
# ══════════════════════════════════════════════════════════════════════════════
def build_recommendation_tab(ws, extracted: dict,
                              scores: dict, risks: dict):
    ws.title = "✅ Recommendation"
    ws.sheet_view.showGridLines = False

    ws.row_dimensions[1].height = 34
    ws.merge_cells("A1:F1")
    c = ws["A1"]
    c.value     = "PURCHASE RECOMMENDATION NOTE"
    c.font      = font(bold=True, color=WHITE, size=13)
    c.fill      = fill(TEAL)
    c.alignment = align("center")

    # sort by score
    ranked = sorted(
        [(v, scores.get(v,{}), risks.get(v,{}))
         for v in extracted],
        key=lambda x: x[1].get("total_score", 0),
        reverse=True
    )

    # filter out disqualified
    qualified = [
        (v, s, r) for v, s, r in ranked
        if not r.get("disqualify_recommended", False)
    ]
    disqualified = [
        (v, s, r) for v, s, r in ranked
        if r.get("disqualify_recommended", False)
    ]

    # column widths
    for ci, w in enumerate([30,22,22,22,22,32], 1):
        ws.column_dimensions[get_column_letter(ci)].width = w

    current_row = 3

    def section_header(title, color=TEAL):
        nonlocal current_row
        ws.row_dimensions[current_row].height = 22
        ws.merge_cells(
            f"A{current_row}:F{current_row}")
        c = ws.cell(row=current_row, column=1,
                    value=title)
        c.font      = font(bold=True, color=WHITE, size=10)
        c.fill      = fill(color)
        c.alignment = align("left")
        current_row += 1

    def detail_row(label, value,
                   label_bg=GRAY_LT, val_bg=WHITE,
                   bold_val=False, val_color="000000"):
        nonlocal current_row
        ws.row_dimensions[current_row].height = 20
        c1 = ws.cell(row=current_row, column=1,
                     value=label)
        c1.font      = font(bold=True, size=9,
                            color=NAVY)
        c1.fill      = fill(label_bg)
        c1.alignment = align("left")
        c1.border    = border()

        ws.merge_cells(
            f"B{current_row}:F{current_row}")
        c2 = ws.cell(row=current_row, column=2,
                     value=value)
        c2.font      = font(bold=bold_val, size=9,
                            color=val_color)
        c2.fill      = fill(val_bg)
        c2.alignment = align("left", wrap=True)
        c2.border    = border()
        current_row += 1

    # ── TOP 3 QUALIFIED ───────────────────────────────────────────────────────
    for pos, (vname, sdata, rdata) in enumerate(
            qualified[:3], 1):
        medal  = {1:"🥇 FIRST CHOICE",
                  2:"🥈 SECOND CHOICE",
                  3:"🥉 THIRD CHOICE"}[pos]
        hdr_c  = {1:TEAL, 2:BLUE2, 3:PURPLE}[pos]
        section_header(f"{medal} — {vname}", hdr_c)

        f      = extracted.get(vname, {})
        total  = sdata.get("total_score", 0)
        summ   = sdata.get("one_line_summary", "")
        lc     = f.get("landed_cost", 0)
        dd     = f.get("delivery_days", "N/A")
        pay    = f.get("payment_terms", "N/A")
        adv    = f.get("advance_percentage", 0) or 0
        certs  = ", ".join(f.get("certifications",[])) or "None"
        pen    = f.get("penalty_clause", "Not mentioned")
        rl     = rdata.get("overall_risk_level","LOW")
        ac     = rdata.get("amber_count", 0)
        summ_r = rdata.get("risk_summary","")

        detail_row("Composite Score",
                   f"{total:.1f} / 100",
                   bold_val=True,
                   val_color=(GREEN_DK if total>=80 else AMBER_DK))
        detail_row("Landed Cost (all-in)",
                   f"INR {lc:.2f} per Kg")
        detail_row("Delivery Lead Time",
                   f"{dd} working days")
        detail_row("Payment Terms",   str(pay))
        detail_row("Advance Required",
                   f"{adv}%" if adv > 0 else "None — full credit")
        detail_row("Certifications",  certs)
        detail_row("Penalty Clause",
                   str(pen) if pen else "None stated")
        detail_row("Risk Level",      rl,
                   val_bg=(GREEN_LT if rl=="LOW" else
                           AMBER_LT if rl=="MEDIUM" else
                           RED_LT))
        detail_row("Amber Flags",
                   f"{ac} flag(s): {summ_r}" if ac>0
                   else "None")
        detail_row("Assessment",      summ,
                   val_bg=GRAY_LT)
        current_row += 1

    # ── DISQUALIFIED ──────────────────────────────────────────────────────────
    if disqualified:
        section_header(
            "⛔ DISQUALIFIED VENDORS — DO NOT SELECT",
            RED_DK)
        for vname, sdata, rdata in disqualified:
            rc   = rdata.get("red_count", 0)
            summ = rdata.get("risk_summary","")
            detail_row(
                vname,
                f"{rc} RED flag(s). {summ}",
                label_bg=RED_LT,
                val_bg=RED_LT,
                val_color=RED_DK)

    # ── approval block ────────────────────────────────────────────────────────
    current_row += 2
    section_header("APPROVAL", NAVY)
    detail_row("Recommended By", "RFQ Intelligence Agent (AI)")
    detail_row("Purchase Manager\nDecision", "_______________________")
    detail_row("Date", "_______________________")
    detail_row("Selected Vendor", "_______________________")
    detail_row("PO to be issued within", "2 working days of approval")


# ══════════════════════════════════════════════════════════════════════════════
# MAIN BUILD FUNCTION
# ══════════════════════════════════════════════════════════════════════════════
def build_excel_report(extracted: dict,
                       scores: dict,
                       risks: dict,
                       output_path: str = "RFQ_Comparison_Report.xlsx",
                       tech_scores: dict         = None,
                       supplier_history: dict    = None,
                       recommendation_reason: str = "",
                       recommendation_details: dict = None):
    wb = Workbook()
    # remove default sheet
    wb.remove(wb.active)

    # build all tabs
    ws1 = wb.create_sheet()
    build_comparison_tab(ws1, extracted, scores, risks)

    ws2 = wb.create_sheet()
    build_scorecard_tab(ws2, scores, risks)

    ws3 = wb.create_sheet()
    build_flags_tab(ws3, risks)

    ws4 = wb.create_sheet()
    build_recommendation_tab(ws4, extracted, scores, risks)

    wb.save(output_path)
    return output_path


#